name: standard_markdown
description: A flutter markdown package which support GFM/CommonMark standard
version: 0.0.4
repository: https://github.com/T2XX/standard_markdown
environment:
  sdk: ^3.1.5

dependencies:
  flutter:
    sdk: flutter
  dart_markdown: ^3.1.7 # generate AST
  get: ^4.6.6 # state control
  flutter_prism: ^0.2.2 # support code highlight
  # markdown_prettier: ^0.1.0-alpha
  flutter_math_fork: ^0.7.2
  markdown_prettier: ^0.1.0-alpha
  markdown_toolbar: ^0.5.0
  super_clipboard: any
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
