name: standard_markdown
description: A flutter markdown package which support GFM/CommonMark standard
version: 1.0.0

environment:
  sdk: ^3.1.5

dependencies:
  dart_markdown: ^3.1.7 # generate AST
  get: ^4.6.6 # state control
  flutter_prism: ^0.2.2 # support code highlight
  markdown_prettier: ^0.1.0-alpha

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
